ALTER TABLE tasks ADD COLUMN project TEXT NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN project TEXT NOT NULL DEFAULT '';
ALTER TABLE memory ADD COLUMN project TEXT NOT NULL DEFAULT '';
ALTER TABLE contexts ADD COLUMN project TEXT NOT NULL DEFAULT '';
ALTER TABLE skills ADD COLUMN project TEXT NOT NULL DEFAULT '';
