use std::path::Path;

use crate::error::CliResult;

const GITIGNORE: &str = "\
.orchy/
events/**/.lock
events/**/checkpoints/
*.tmp
";

const GITATTRIBUTES: &str = "\
events/** -merge
journal/** merge=union
";

const ORCHY_TOML: &str = "\
[vault]
name = \"vault\"

[events]
# Fixed when this machine's log is first created; changing it afterwards is refused.
partitions = 10

[recall]
default_limit = 20

[audit]
stale_after_days = 180
";

const AGENTS_MD: &str = "\
# Working in this vault

This directory is an orchy vault: markdown documents with typed frontmatter, a task board,
and a message board between agents.

The root is fixed — `docs/`, `tasks/`, `messages/`, `agents/`, `events/` — and your own
documents live under `docs/`, where their namespace shapes the tree however you like.

Frontmatter is the only source of truth. A file's directory is a projection of its
frontmatter, never the other way round, so never infer state from a path.

Every document has a stable `id`. Move or rename files freely; links travel with the id.
";

const INDEX_MD: &str = "\
# Vault

Generated by `orchy index`. Browse `tasks/`, `messages/` and `agents/`, or run
`orchy recall <query>`.
";

pub(crate) fn scaffold(root: &Path) -> CliResult<Vec<String>> {
    let mut written = Vec::new();
    std::fs::create_dir_all(root)?;

    for (name, contents) in [
        (".gitignore", GITIGNORE),
        (".gitattributes", GITATTRIBUTES),
        ("orchy.toml", ORCHY_TOML),
        ("AGENTS.md", AGENTS_MD),
        ("index.md", INDEX_MD),
    ] {
        let path = root.join(name);
        if path.exists() {
            continue;
        }
        std::fs::write(&path, contents)?;
        written.push(name.to_owned());
    }

    for dir in [
        "docs",
        "tasks/open",
        "tasks/done",
        "messages",
        "agents",
        "events",
    ] {
        std::fs::create_dir_all(root.join(dir))?;
    }

    let claude = root.join("CLAUDE.md");
    if !claude.exists() {
        #[cfg(unix)]
        std::os::unix::fs::symlink("AGENTS.md", &claude)?;
        written.push("CLAUDE.md".to_owned());
    }

    Ok(written)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_fresh_directory_becomes_a_vault() {
        let temp = tempfile::tempdir().unwrap();
        let written = scaffold(temp.path()).unwrap();

        assert!(written.contains(&"orchy.toml".to_owned()));
        for expected in [".gitignore", ".gitattributes", "AGENTS.md", "index.md"] {
            assert!(temp.path().join(expected).exists(), "{expected} missing");
        }
        for dir in [
            "docs",
            "tasks/open",
            "tasks/done",
            "messages",
            "agents",
            "events",
        ] {
            assert!(temp.path().join(dir).is_dir(), "{dir} missing");
        }
    }

    #[test]
    fn the_gitignore_keeps_runtime_state_out_of_git() {
        let temp = tempfile::tempdir().unwrap();
        scaffold(temp.path()).unwrap();
        let ignored = std::fs::read_to_string(temp.path().join(".gitignore")).unwrap();
        assert!(ignored.contains(".orchy/"));
        assert!(ignored.contains("*.tmp"));
    }

    #[test]
    fn the_event_log_is_marked_unmergeable() {
        let temp = tempfile::tempdir().unwrap();
        scaffold(temp.path()).unwrap();
        let attributes = std::fs::read_to_string(temp.path().join(".gitattributes")).unwrap();
        assert!(
            attributes.contains("events/** -merge"),
            "a union-merged log would interleave offsets from two machines"
        );
    }

    #[test]
    fn running_twice_does_not_clobber_an_edited_scaffold() {
        let temp = tempfile::tempdir().unwrap();
        scaffold(temp.path()).unwrap();
        std::fs::write(temp.path().join("AGENTS.md"), "my own notes").unwrap();

        let second = scaffold(temp.path()).unwrap();
        assert!(second.is_empty(), "nothing should be rewritten");
        assert_eq!(
            std::fs::read_to_string(temp.path().join("AGENTS.md")).unwrap(),
            "my own notes"
        );
    }
}
