[package]
name = "orchy-core"
description = "orchy domain: aggregates, value objects, domain events and ports"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
eventuary.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
thiserror.workspace = true
ulid.workspace = true

[lints]
workspace = true
