[package]
name = "orchy-events"
edition.workspace = true
version.workspace = true

[dependencies]
uuid.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
futures = "0.3"
either.workspace = true
tokio-util.workspace = true

[lints]
workspace = true
